### ISSUE TITLE
Lucene upgrade cause exception on startup

### ISSUE THREAD

**Issue by olatignies** [kaicode/srqs#4]
java.lang.IllegalArgumentException: Could not load codec 'Lucene40'.  Did you forget to add lucene-backward-codecs.jar?

Prevent from upgrading to new 20170131 version.

java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene40' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene54]

**Comment by olatignies** [comment]
Found the solution, when you upgrade the Snomed release, you should clean the index folder before loading the new version. As the previous index was indexed with Lucene version 40, it just try to update the index, but this specific version is not available in the most recent version (migrated to version 5).

**Comment by kaicode** [comment]
Hi @olatignies, yes that's a good catch! Thank you. I'll update the README.
