### ISSUE TITLE
Advice/Help required

### ISSUE THREAD

**Issue by mikebhart** [kaicode/srqs#8]
Hi there, Im working on  a project where I need to get snomed data in the form of json.  The data I want to bring back is a list of subjects like so:-

Taxonomy
CommunicateAction 
Communication and information management 
Event 
Awards 
Conferences and meetings 
Webinar
Media 
Publishing
Social networking 
Health communication and promotion
DiagnosticProcedure 
Diagnosis 
Diagnostic errors 
Diagnostic techniques and procedures 
Differential diagnosis 
Prognosis
Drug 
Medicines 
Pharmaceutical preparations 
Biosimilar pharmaceuticals 
Combination products 
Complementary and alternative medicines 
Homeopathy
Dosage forms 
Capsules 

etc .  Can I use this query service to bring back this data or is there some website I can go to and just download a file?

Much appreciated

**Comment by kaicode** [comment]
Hello. This project is for querying the content within the SNOMED CT ontology which is [browsable here](https://browser.ihtsdotools.org/). The information you have requested does not seem to align well with the content available.
Closing this ticket for now but feel free to reopen it if you have a more specific question. Thanks.

**Comment by mikebhart** [comment]
Hi there, do you know where i can the information I need?

**Comment by kaicode** [comment]
Your query seems too vague for me to be able to help. Sorry.

**Comment by mikebhart** [comment]
Hi there.  What im trying to do is get a dataset like belows image attachment. Any ideas?
![subjects](https://user-images.githubusercontent.com/19751493/101512724-3d748200-3973-11eb-9d28-11f0bf4f4e7d.jpg)

**Comment by kaicode** [comment]
Hi @mikebhart, thanks for providing more information about your requirements.

I would recommend:
-  using the [SNOMED Browser](https://browser.ihtsdotools.org/?perspective=full&conceptId1=103693007&edition=MAIN/2020-07-31&release=&languages=en) to find the most general concepts align with your requirements
   - For example `103693007 | Diagnostic procedure (procedure) |` and `373873005 | Pharmaceutical / biologic product (product) |`
- You could then use the snomed-query-service to fetch the concepts within each of these areas using an ECL (Expression Constraint Language) query.
   - Load a SNOMED CT release by following the [readme](https://github.com/IHTSDO/snomed-query-service#quick-start), bear in mind that Java 8 is required at the moment to run the jar.
   - For example fetch all descendants and self of `103693007 | Diagnostic procedure (procedure) |` using the ECL `<<103693007` like this: http://localhost:8080/concepts?ecQuery=%3C%3C103693007
<img width="587" alt="Screenshot 2020-12-08 at 16 58 11" src="https://user-images.githubusercontent.com/2010517/101515745-97c31200-3976-11eb-8e41-89ee361cbc59.png">

Concepts are fetched 1,000 at a time. The response has pagination using the `offset` parameter.

**FSN vs PT**
This project only currently supports fetching the concept id and FSN or Fully Specified Name of a concept. This is the most concise name but it's often not the name used by clinicians or in medical records so the usefulness depends on your use-case. 

**Using Snowstorm instead**
Running ECL against the Snowstorm terminology server also gives you the PT or Preferred Term. This may be more helpful. e.g. https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/MAIN/2020-07-31/concepts?limit=1000&ecl=%3C%3C103693007
The public snowstorm instance has rate limiting so requests will be blocked from scripts making requests too quickly.

I hope this helps!

kind regards,
Kai Kewley
