### ISSUE TITLE
Error loading realease of snomed

### ISSUE THREAD

**Issue by Allae-Ghayat** [kaicode/srqs#9]
I am trying to load a version of snomed to test the application to see how the ecl works but I get an error when executing the command. Any suggestions? 
<img width="1371" alt="image" src="https://github.com/IHTSDO/snomed-query-service/assets/48176134/35e2aaac-dd5c-4eb7-a23f-a47237bd84f0">

**Comment by Allae-Ghayat** [comment]
I don't know which release ti pick so I picked a spanish version

**Comment by pgwilliams** [comment]
Ah, I suspect we're still seeing issues dropping out as we've shifted from Java 11 to Java 17.

What version of Java are you using there @Allae-Ghayat ?   Type  `java --version` to find out.

Could you try adding `  --add-opens java.base/java.lang=ALL-UNNAMED` as a command line parameter just after the -Xms3g ?

**Comment by Allae-Ghayat** [comment]
Good morning, I've managed to fix it, thank you very much.

**Comment by CoderMChu** [comment]
@Allae-Ghayat  Can you check out the latest version in GitHub and run java -Xms3g -jar snomed-query-service-4.0.0-exec.jar --loadRelease= 
See more information in https://github.com/IHTSDO/snomed-query-service/blob/master/README.md

**Comment by pgwilliams** [comment]
Oh that's great @Allae-Ghayat.   What did you do to fix it please?

**Comment by Allae-Ghayat** [comment]
I was trying to load the terminology with the .jar but I decided to download the source code and import it through an IDE, I used eclipse to import it. I don't know why it let me import it with the source code and I had problems with the jar, but I needed the source code to debug how to work with the ECL so it was good for me to download it.
Un saludo

**Comment by Allae-Ghayat** [comment]
l
